name: Snapcraft

on:
  - push
  - pull_request

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: snapcore/action-build@v1
      id: build
    - id: run-help
      run: |
        sudo snap install --devmode --dangerous ${{ steps.build.outputs.snap }}
        buck --help
    - id: publish
      if: ${{ github.event_name == 'push' }}
      uses: snapcore/action-publish@v1
      env:
        # See: https://github.com/snapcore/action-publish#store-login
        # $ snapcraft export-login --channels edge --snaps=buck --acls package_access,package_push,package_update,package_release,package_access -
        SNAPCRAFT_STORE_CREDENTIALS: ${{ secrets.SNAPCRAFT_STORE_CREDENTIALS }}
      with:
        snap: ${{ steps.build.outputs.snap }}
        release: edge
